<declarationseq>::=<declaration> <declarationseq>|<declaration>
<declaration>::=<templateDeclaration>|<simpleDeclaration>
<templateDeclaration>::=<Template> <Less> <Typename_> <Greater> <declaration>
<simpleDeclaration>::=<declSpecifierSeq> <Semi>
<declSpecifierSeq>::=<declSpecifier> <declSpecifierSeq>|<declSpecifier>
<declSpecifier>::=<Typedef>|<typeSpecifier>
<typeSpecifier>::=<classSpecifier>|<trailingTypeSpecifier>
<classSpecifier>::=<classHead> <LeftBrace> <RightBrace>|<classHead> <LeftBrace> <memberdeclaration> <RightBrace>
<memberdeclaration>::=<declSpecifierSeq> <Semi>
<trailingTypeSpecifier>::=<simpleTypeSpecifier>
<simpleTypeSpecifier>::=<theTypeName>
<theTypeName>::=<simpleTemplateId>|Identifier|<className>
<simpleTemplateId>::=<templateName> <Less> <Int> <Greater>
<templateName>::=Identifier
<classHead>::=<classKey> <className>
<classKey>::=<Struct>|<Class>
<className>::=<simpleTemplateId>|Identifier
<Template>::=template
<Less>::=<
<Greater>::=>
<Semi>::=;
<LeftBrace>::={
<RightBrace>::=}
<Struct>::=struct
<Class>::=class
<Int>::=int
<Typedef>::=typedef
<Typename_>::=typename