<program>::=<simpleDeclaration>|<simpleDeclaration> <program>
<simpleDeclaration>::=<classSpecifier> <Semi>
<classSpecifier>::=<classHead> <LeftBrace> <RightBrace> |<classHead>
<classHead>::=<Union>|<Union> <classHeadName>|<classKey>|<classKey> <classHeadName>
<classHeadName>::=<className>|<nestedNameSpecifier> <className>
<classKey>::=<Struct>|<Class>
<nestedNameSpecifier>::=<Doublecolon>
<className>::=Identifier
<Semi>::=;
<LeftBrace>::={
<RightBrace>::=}
<Union>::=union
<Struct>::=struct
<Class>::=class
<Doublecolon>::=::