<program> ::= <expression>|<expression> <program>
<expression> ::= <charExpression>|<intExpression>|<floatExpression>
<charExpression> ::= char Identifier ;
<intExpression> ::= int Identifier ;
<floatExpression> ::= float Identifier ;